apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: plugin-barman-cloud
    app.kubernetes.io/managed-by: kustomize
  name: barman-plugin-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: barman-plugin-leader-election-role
subjects:
- kind: ServiceAccount
  name: plugin-barman-cloud
  namespace: cnpg-system
